name: cicd

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_and_deploy:
        name: Build and Deploy App
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.10.x
                cache: 'pip'
            
            - name: Install AWS CDK
              run: npm install -g aws-cdk

            - name: Install Dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run Linting Tools
              run: |
                pip install flake8
                flake8 --verbose .
            
            - name: Package Lambdas
              run: |
                for lambda in ./*/
                do
                    cd ${lambda%*/}
                    pip install -r requirements.txt --target .
                    cd ..
                done
              working-directory: ${{ github.workspace }}/src
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Run CDK Synth
              run: cdk synth 
            
            - name: Run CDK Deploy
              run: cdk deploy
